spring:
  profiles:
    active: prod
    include: secret
  servlet:
    multipart:
      max-file-size: 10MB # 개별 파일 최대 크기
      max-request-size: 10MB # 요청당 최대 크기

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG # JPA 관련 로그메시지 DEBUG 레벨로 출력 -> 분리할 것

server:
  servlet:
    encoding:
      force-response: true # 모든 응답의 문자 인코딩을 강제