spring:
  datasource: # 데이터베이스 설정
    url: ${DOLPHIN_DEV_DATABASE_URL}
    username: ${DOLPHIN_DEV_DATABASE_USERNAME}
    password: ${DOLPHIN_DEV_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 서버 시작 시 변경사항만 update
    show-sql: true      # 쿼리문 보여줌
    properties:
      hibernate:
        format_sql: true  # 쿼리문 가독성 있게 띄워줌
#        use_sql_comments: true # JPQL 쿼리문 보기
        default_batch_fetch_size: 100