spring:
  profiles:
    active: dev
    include: secret

logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
    multipart:
      enabled: true
#      file-size-threshold: 2MB
#      max-file-size: 10MB
#      max-request-size: 10MB
