#jwt 관련 정보
jwt:
  key: ${MTWC_JWT_SECRET}
  access-token-expiration-seconds: 43200 # 60 * 60 * 12 = 12시간
  refresh-token-expiration-seconds: 86400 # 60 * 60 * 24 = 24시간

mail: #관리자 권한 메일
  address:
    admin: ${MTWC_ADMIN_EMAIL_1}
#payment:
#  cid: TC0ONETIME   #가맹점 임시 코드
#  admin_key: test #카카오 어플리케이션 어드민 키
#  host: https://kapi.kakao.com/v1/payment
#  url: http://localhost:8080
#

# OAuth2.0
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${MTWC_G_CLIENT_ID}
            clientSecret: ${MTWC_G_CLIENT_SECRET}
            scope:
              - email
              - profile

# Database 설정
  datasource:
    url: ${DOLPHIN_DEV_DATABASE_URL}
    username: ${DOLPHIN_DEV_DATABASE_USERNAME}
    password: ${DOLPHIN_DEV_DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

# 네이버 검색 API
naver:
  search:
    api:
      id: ${DOLPHIN_NAVER_SEARCH_API_ID}
      secret: ${DOLPHIN_NAVER_SEARCH_API_SECRET}

# 이미지 서버 - imgbb
imgbb:
  secret: ${DOLPHIN_IMGBB_SECRET_KEY}